import autosize from "autosize";

import "./src/core.dialog.js";
import "./src/accordion/accordion.widget.js";
import "./src/autocomplete/autocomplete.widget.js";
import "./src/blockui/blockui.widget.js";
import "./src/carousel/carousel.widget.js";
import "./src/confirmpopup/confirmpopup.widget.js";
import "./src/columntoggler/columntoggler.widget.js";
import "./src/dashboard/dashboard.widget.js";
import "./src/datagrid/datagrid.widget.js";
import "./src/datalist/datalist.widget.js";
import "./src/datascroller/datascroller.widget.js";
import "./src/datatable/datatable.widget.js";
import "./src/datatable/datatable.frozen.widget.js";
import "./src/dialog/dialog.widget.js";
import "./src/dragdrop/dragdrop.widget.js";
import "./src/effect/effect.widget.js";
import "./src/fieldset/fieldset.widget.js";
import "./src/forms/forms.inputtext.widget.js";
import "./src/forms/forms.inputtextarea.widget.js";
import "./src/forms/forms.selectonemenu.widget.js";
import "./src/forms/forms.selectoneradio.widget.js";
import "./src/forms/forms.selectbooleancheckbox.widget.js";
import "./src/forms/forms.selectmanycheckbox.widget.js";
import "./src/forms/forms.selectlistbox.widget.js";
import "./src/forms/forms.selectonelistbox.widget.js";
import "./src/forms/forms.selectmanymenu.widget.js";
import "./src/forms/forms.cascadeselect.widget.js";
import "./src/forms/forms.commandbutton.widget.js";
import "./src/forms/forms.commandlink.widget.js";
import "./src/forms/forms.button.widget.js";
import "./src/forms/forms.linkbutton.widget.js";
import "./src/forms/forms.selectmanybutton.widget.js";
import "./src/forms/forms.selectonebutton.widget.js";
import "./src/forms/forms.selectbooleanbutton.widget.js";
import "./src/forms/forms.selectcheckboxmenu.widget.js";
import "./src/forms/forms.password.widget.js";
import "./src/forms/forms.defaultcommand.widget.js";
import "./src/forms/forms.splitbutton.widget.js";
import "./src/forms/forms.multiselectlistbox.widget.js";
import "./src/growl/growl.widget.js";
import "./src/inplace/inplace.widget.js";
import "./src/menu/menu.base.widget.js";
import "./src/menu/menu.breadcrumb.widget.js";
import "./src/menu/menu.tieredmenu.widget.js";
import "./src/menu/menu.menubar.widget.js";
import "./src/menu/menu.slidemenu.widget.js";
import "./src/menu/menu.plainmenu.widget.js";
import "./src/menu/menu.menubutton.widget.js";
import "./src/menu/menu.contextmenu.widget.js";
import "./src/menu/menu.megamenu.widget.js";
import "./src/menu/menu.panelmenu.widget.js";
import "./src/menu/menu.steps.widget.js";
import "./src/menu/menu.tabmenu.widget.js";
import "./src/message/message.widget.js";
import "./src/messages/messages.widget.js";
import "./src/notificationbar/notificationbar.widget.js";
import "./src/panel/panel.widget.js";
import "./src/orderlist/orderlist.widget.js";
import "./src/outputpanel/outputpanel.widget.js";
import "./src/overlaypanel/overlaypanel.widget.js";
import "./src/paginator/paginator.widget.js";
import "./src/picklist/picklist.widget.js";
import "./src/progressbar/progressbar.widget.js";
import "./src/rating/rating.widget.js";
import "./src/resizable/resizable.widget.js";
import "./src/slider/slider.widget.js";
import "./src/spinner/spinner.widget.js";
import "./src/splitter/splitter.widget.js";
import "./src/spotlight/spotlight.widget.js";
import "./src/speeddial/speeddial.widget.js";
import "./src/staticmessage/staticmessage.widget.js";
import "./src/sticky/sticky.widget.js";
import "./src/tabview/tabview.widget.js";
import "./src/tagcloud/tagcloud.widget.js";
import "./src/tooltip/tooltip.widget.js";
import "./src/tree/tree.base.widget.js";
import "./src/tree/tree.vertical.widget.js";
import "./src/tree/tree.horizontal.widget.js";
import "./src/treetable/treetable.widget.js";
import "./src/wizard/wizard.widget.js";
import "./src/tristatecheckbox/tristatecheckbox.widget.js";
import "./src/chip/chip.widget.js";
import "./src/chips/chips.widget.js";
import "./src/scrolltop/scrolltop.widget.js";
import "./src/sidebar/sidebar.widget.js";
import "./src/dataview/dataview.widget.js";
import "./src/toggleswitch/toggleswitch.widget.js";

declare global {
    interface Window {
        autosize: typeof autosize;
    }
}

// Expose autosize to the global scope
Object.assign(window, { autosize });
