version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "commons-io:commons-io"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
