# Global cache doesn't work with esbuild when cache folder is on a different
# drive in Windows.
# See https://github.com/evanw/esbuild/issues/3131
enableGlobalCache: false

nodeLinker: pnp

pnpEnableInlining: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs
