enableGlobalCache: false

nodeLinker: pnp

pnpEnableInlining: false

yarnPath: .yarn/releases/yarn-4.9.2.cjs

httpProxy: "http://172.30.30.13:3128"
httpsProxy: "http://172.30.30.13:3128"

enableStrictSsl: false