Steps are defined as child menuitem components in breadcrumb.

[source, xml]
----
<p:breadCrumb>
    <p:menuitem label="Categories" url="#" />
    <p:menuitem label="Sports" url="#" />
</p:breadCrumb>
----

==== Dynamic Menus
Menus can be created programmatically as well, see the dynamic menus part in menu component
section for more information and an example.

==== Options Facet
In order to place custom content inside breadcrumb, options facet is provided. Options facet content
is aligned right by default.

==== Skinning
Breadcrumb resides in a container element that `style` and `styleClass` options apply. Following is the
list of structural style classes;

```
Style Class Applies
.ui-breadcrumb Main breadcrumb container element.
.ui-breadcrumb .ui-menu-item-link Each menuitem.
.ui-breadcrumb .ui-menu-item-text Each menuitem label.
.ui-breadcrumb-chevron Seperator of menuitems.
```
As skinning style classes are global, see the main theming section for more information.

==== Tips

- If there is a dynamic flow, use model option instead of creating declarative p:menuitem
    components and bind your MenuModel representing the state of the flow.
- Breadcrumb can do ajax/non-ajax action requests as well since p:menuitem has this option. In this
    case, breadcrumb must be nested in a form.
- url option is the key for a menuitem, if it is defined, it will work as a simple link. If you’d like to
    use menuitem to execute command with or without ajax, do not define the url option.