Carousel has two main use-cases; data and general content display. To begin with data iteration let’s
use a list of cars to display with carousel.

[source, java]
----
public class Car {
    private String model;
    private int year;
    private String manufacturer;
    private String color;
    // Getters/Setters
----

[source, xml]
----
public class CarBean {
    private List<Car> cars;
    public CarListController() {
        cars = new ArrayList<Car>();
        cars.add(new Car("myModel", 2005, "ManufacturerX", "blue"));
    }

    // Getter/Setters
}
----

[source, xml]
----
<p:carousel value="#{carBean.cars}" var="car">
    <p:graphicImage value="/images/cars/#{car.manufacturer}.jpg"/>
    <h:outputText value="Model: #{car.model}" />
    <h:outputText value="Year: #{car.year}" />
    <h:outputText value="Color: #{car.color}" />
</p:carousel>
----

Carousel iterates through the cars collection and renders it’s children for each car.

==== Limiting Visible Items
Bu default carousel lists its items in pages with size 3. This is customizable with the rows attribute.

[source, xml]
----
<p:carousel value="#{carBean.cars}" var="car" numVisible="1" itemStyle="width:200px" >
    // content
</p:carousel>
----

==== Effects

Paging happens with a slider effect by default and following easing options are supported.

- backBoth
- backIn
- backOut
- bounceBoth
- bounceIn
- bounceOut
- easeBoth
- easeBothStrong
- easeIn
- easeInStrong
- easeNone
- easeOut
- easeInOutCirc
- easeOutStrong
- elasticBoth
- elasticIn
- elasticOut

==== SlideShow
Carousel can display the contents in a slideshow, for this purpose `autoPlayInterval` and `circular`
attributes are used. Following carousel displays a collection of images as a slideshow.

[source, xml]
----
<p:carousel autoPlayInterval="2000" rows="1" effect="easeInStrong" circular="true" itemStyle=”width:200px” >
    <p:graphicImage value="/images/nature1.jpg"/>
    <p:graphicImage value="/images/nature2.jpg"/>
    <p:graphicImage value="/images/nature3.jpg"/>
    <p:graphicImage value="/images/nature4.jpg"/>
</p:carousel>
----

==== Content Display
Another use case of carousel is tab based content display.

[source, xml]
----
<p:carousel rows="1" itemStyle="height:200px;width:600px;">
    <p:tab title="Godfather Part I">
        <h:panelGrid columns="2" cellpadding="10">
            <p:graphicImage value="/images/godfather/godfather1.jpg" />
            <h:outputText value="The story begins as Don Vito ..." />
        </h:panelGrid>
    </p:tab>

    <p:tab title="Godfather Part II">
        <h:panelGrid columns="2" cellpadding="10">
            <p:graphicImage value="/images/godfather/godfather2.jpg" />
            <h:outputText value="Francis Ford Coppola's ..."/>
        </h:panelGrid>
    </p:tab>

    <p:tab title="Godfather Part III">
        <h:panelGrid columns="2" cellpadding="10">
            <p:graphicImage value="/images/godfather/godfather3.jpg" />
            <h:outputText value="After a break of ..." />
        </h:panelGrid>
    </p:tab>
</p:carousel>
----

==== Item Selection
Sample below selects an item from the carousel and displays details within a dialog.

[source, xml]
----
<h:form id=”form">
    <p:carousel value="#{carBean.cars}" var="car" itemStyle=”width:200px” >
        <p:graphicImage value="/images/cars/#{car.manufacturer}.jpg"/>
        <p:commandLink update=":form:detail" oncomplete="PF('dlg').show()">
            <h:outputText value="Model: #{car.model}" />
            <f:setPropertyActionListener value="#{car}" target="#{carBean.selected}" />
        </p:commandLink>
    </p:carousel>

    <p:dialog widgetVar="dlg">
        <h:outputText id="detail" value="#{carBean.selected}" />
    </p:dialog>
</h:form>
----

[source, java]
----
public class CarBean {
    private List<Car> cars;
    private Car selected;
    // Getters/Setters
}
----

==== Header and Footer
Header and Footer of carousel can be defined in two ways either, using `headerText` and `footerText`
options that take simple strings as labels or by `header` and `footer` facets that can take any custom
content.

==== Responsive
When responsive mode is enabled via setting responsive option to true, carousel switches between
small and large viewport depending on the breakpoint value which is 560 by default.

==== Skinning
Carousel resides in a container element which `style` and `styleClass` options apply. `itemStyle` and
`itemStyleClass` attributes apply to each item displayed by carousel. Following is the list of structural
style classes;

```
Style Class Applies
.ui-carousel Main container
.ui-carousel-header Header container
.ui-carousel-header-title Header content
.ui-carousel-viewport Content container
.ui-carousel-button Navigation buttons
.ui-carousel-next-button Next navigation button of paginator
.ui-carousel-prev-button Prev navigation button of paginator
.ui-carousel-page-links Page links of paginator.
.ui-carousel-page-link Each page link of paginator.
.ui-carousel-item Each item.
```
As skinning style classes are global, see the main theming section for more information.

