include::p-autoComplete[]

==== Getting Started with AutoComplete
AutoComplete is an input component so it requires a value as usual. Suggestions are loaded by
calling a server side completeMethod that takes a single string parameter which is the text entered.

[source, xml]
----
<p:autoComplete value="#{bean.text}" completeMethod="#{bean.complete}" />
----

[source, java]
----
public class Bean {

    private String text;

    public List < String > complete(String query) {
        List < String > results = new ArrayList < String > ();
        for (int i = 0; i < 10; i++)
            results.add(query + i);
        return results;
    }
    //getter setter
}
----

==== Pojo Support
Most of the time, instead of simple strings you would need work with your domain objects,
autoComplete supports this common use case with the use of a converter and data iterator.
Following example loads a list of players, itemLabel is the label displayed as a suggestion and
itemValue is the submitted value. Note that when working with pojos, you need to plug-in your own
converter.

[source, xml]
----
<p:autoComplete value="#{playerBean.selectedPlayer}"
                completeMethod="#{playerBean.completePlayer}"
                var="player"
                itemLabel="#{player.name}"
                itemValue="#{player}"
                converter="playerConverter"/>
----

[source, java]
----
public class PlayerBean {
    private Player selectedPlayer;
    public Player getSelectedPlayer() {
        return selectedPlayer;
    }
    public void setSelectedPlayer(Player selectedPlayer) {
        this.selectedPlayer = selectedPlayer;
    }
    public List < Player > complete(String query) {
        List < Player > players = readPlayersFromDatasource(query);
        return players;
    }
}

public class Player {
    private String name;
    //getter setter
}
----

==== Limiting the Results
Number of results shown can be limited, by default there is no limit. When the suggestions exceed
the number of results, a text defined by `moreText` is displayed to indicate this case. There is no
default action when the moreText is clicked, you need to use `moreText` ajax behavior event to handle
more results.

[source, xml]
----
<p:autoComplete value="#{bean.text}" completeMethod="#{bean.complete}" maxResults="5" />
----

==== Minimum Query Length
By default queries are sent to the server and completeMethod is called as soon as users starts typing
at the input text. This behavior is tuned using the `minQueryLength` attribute.

[source, xml]
----
<p:autoComplete value="#{bean.text}" completeMethod="#{bean.complete}" minQueryLength="3" />
----

With this setting, suggestions will start when user types the 3rd character at the input field.

==== Query Delay
AutoComplete is optimized using `queryDelay` option, by default autoComplete waits for 300
milliseconds to query a suggestion request, if you’d like to tune the load balance, give a longer
value. Following autoComplete waits for 1 second after user types an input.

[source, xml]
----
<p:autoComplete value="#{bean.text}" completeMethod="#{bean.complete}" queryDelay="1000" />
----

==== Custom Content
AutoComplete can display custom content by nesting columns.

[source, xml]
----
<p:autoComplete value="#{autoCompleteBean.selectedPlayer}"
                completeMethod="#{autoCompleteBean.completePlayer}"
                var="p"
                itemValue="#{p}"
                converter="player">
    <p:column>
        <p:graphicImage value="/images/barca/#{p.photo}" width="40" height="50"/>
    </p:column>

    <p:column>
        #{p.name} - #{p.number}
    </p:column>
</p:autoComplete>
----

==== Dropdown Mode
When dropdown mode is enabled, a dropdown button is displayed next to the input field.
Depending on dropdownMode configuration, clicking this button will either do a search with an
empty query or search with the current value in input.

[source, xml]
----
<p:autoComplete value="#{bean.text}" completeMethod="#{bean.complete}" dropdown="true" />
----

==== Multiple Selection
AutoComplete supports multiple selection as well, to use this feature set multiple option to true and
define a list as your backend model. Following example demonstrates multiple selection with
custom content support.

[source, xml]
----
<p:autoComplete id="advanced"
                value="#{autoCompleteBean.selectedPlayers}"
                completeMethod="#{autoCompleteBean.completePlayer}"
                var="p"
                itemLabel="#{p.name}"
                itemValue="#{p}"
                converter="player"
                multiple="true">
    <p:column style="width:20%;text-align:center">
        <p:graphicImage value="/images/barca/#{p.photo}"/>
    </p:column>

    <p:column style="width:80%">
        #{p.name} - #{p.number}
    </p:column>
</p:autoComplete>
----

[source, java]
----
public class AutoCompleteBean {
    private List < Player > selectedPlayers;
    // getter setter
}
----

==== Caching
Suggestions can be cached on client side so that the same query does not do a request which is
likely to return same suggestions again. To enable this, set `cache` option to true. There is also a
`cacheTimeout` option to configure how long it takes to clear a cache automatically.

[source, xml]
----
<p:autoComplete value="#{bean.text}" completeMethod="#{bean.complete}" cache="true"/>
----

==== Ajax Behavior Events
Instead of waiting for user to submit the form manually to process the selected item, you can enable
instant ajax selection by using the `itemSelect` ajax behavior. Example below demonstrates how to
display a message about the selected item instantly.

[source, xml]
----
<p:autoComplete value="#{bean.text}" completeMethod="#{bean.complete}">
    <p:ajax event="itemSelect" listener="bean.handleSelect" update="msg" />
</p:autoComplete>

<p:messages id=”msg” />
----

[source, java]
----
public class Bean {
    public void handleSelect(SelectEvent event) {
        Object item = event.getObject();
        FacesMessage msg = new FacesMessage("Selected", "Item:" + item);
    }
}
----

Your listener (if defined) will be invoked with an _org.primefaces.event.Select_ instance that contains a
reference to the selected item. Note that autoComplete also supports events inherited from regular
input text such as blur, focus, mouseover in addition to `itemSelect`. Similarly, `itemUnselect` event is provided for multiple autocomplete when an item is removed by clicking the remove icon. In this
case `org.primefaces.event.Unselect` instance is passed to a listener if defined.

|===
|Event Listener | Parameter | Fired

|itemSelect | org.primefaces.event.SelectEvent | On item selection
|itemUnselect | org.primefaces.event.UnselectEvent | On item unselection
|query | - | On query
|moreText | - | When moreText is clicked
|===

==== ItemTip
Itemtip is an advanced built-in tooltip when mouse is over on suggested items. Content of the
tooltip is defined via the `itemtip` facet.

[source, xml]
----
<p:autoComplete value="#{autoCompleteBean.selectedPlayer1}"
                id="basicPojo"
                completeMethod="#{autoCompleteBean.completePlayer}"
                var="p"
                itemLabel="#{p.name}"
                itemValue="#{p}"
                converter="player">
    <f:facet name="itemtip">
        <h:panelGrid columns="2" cellpadding="5">
            <f:facet name="header">
                <p:graphicImage value="/images/barca/#{p.photo}" />
            </f:facet>
            <h:outputText value="Name: " />
            <h:outputText id="modelNo" value="#{p.name}" />
            <h:outputText value="Number " />
            <h:outputText id="year" value="#{p.number}" />
            <h:outputText value="Position " />
            <h:outputText value="#{p.position}"/>
        </h:panelGrid>
    </f:facet>
</p:autoComplete>
----

==== Client Side API
.Widget: _PrimeFaces.widget.AutoComplete_
|===
|Method | Params | Return Type | Description

|search(value) | keyword for search | void | Initiates a search with given value
|close() | - | void | Hides suggested items menu
|disable() | - | void | Disables the input field
|enable() | - | void | Enables the input field
|deactivate()| - | void |Deactivates search behavior
|activate() - void Activates search behavior
|===

==== Skinning
Following is the list of structural style classes;

|===
|Class | Applies
|.ui-autocomplete |Container element.
|.ui-autocomplete-input | Input field.
|.ui-autocomplete-panel | Container of suggestions list.
|.ui-autocomplete-items | List of items
|.ui-autocomplete-item | Each item in the list.
|.ui-autocomplete-query | Highlighted part in suggestions.
|===

As skinning style classes are global, see the main theming section for more information.

==== Tips

- Do not forget to use a converter when working with pojos.
- Enable forceSelection if you would like to accept values only from suggested list.
- Increase query delay to avoid unnecessary load to server as a result of user typing fast.
- Use emptyMessage option to provide feedback to the users that there are no suggestions.
- Enable caching to avoid duplicate queries.
