package org.primefaces.jsfunit;

import org.jboss.jsfunit.jsfsession.JSFClientSession;


//Could be generated by maven-jsf-plugin for each component client.
public class PrimeClientFactory {
    
    private static JSFClientSession client;

    public PrimeClientFactory(JSFClientSession client) {
        this.client = client;
    }
    
    public static SpinnerClient spinnerClient() {
        return new SpinnerClient(client);
    }
    
    public static SpinnerClient spinnerClient(JSFClientSession client) {
        return new SpinnerClient(client);
    }
    
    public static SpinnerClient spinnerClient(JSFClientSession client, String componentId) {
        return new SpinnerClient(client, componentId);
    }
}
